export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_PRODUCT = "ADD_PRODUCT";

export const ADD_CART = "ADD_CART";

export const REMOVE_CART = "REMOVE_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
export const ADD_LATEST_PRODUCT = "ADD_LATEST_PRODUCT";
export const ADD_FILTER_PRODUCTS = "ADD_FILTER_PRODUCTS";
export const SHOW_SEARCH_BAR = "SHOW_SEARCH_BAR";
export const WISHLIST_CHANGED = "WISHLIST_CHANGED";
